import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata = {
    "kernelspec": {"display_name": "venv_pytorch", "language": "python", "name": "venv_pytorch"},
    "language_info": {"name": "python", "version": "3.13.9"},
}

def md(src):  return nbf.v4.new_markdown_cell(src)
def code(src): return nbf.v4.new_code_cell(src)

C = []  # cells list

# ── 1 · Title ─────────────────────────────────────────────────────────────────
C.append(md(
"# Enhanced Virtual Try-On — CP-VTON Style Pipeline\n"
"## MSDS Computer Vision 462 · Final Project\n\n"
"| | |\n|---|---|\n"
"| **Team** | Joyati · Biraj Mishra · Murughanandam S. |\n"
"| **Course** | MSDS COMPUTERVISION 462 |\n"
"| **Date** | Spring 2026 |\n\n---\n\n"
"## Abstract\n\n"
"This notebook implements a **two-stage image-based virtual try-on** pipeline inspired by\n"
"**CP-VTON** (Wang et al., ECCV 2018), using genuine computer-vision components:\n\n"
"| Stage | Module | CV Technique |\n|---|---|---|\n"
"| 1 | **Geometric Matching Module (GMM)** | CNN feature extraction → cross-correlation → TPS warping |\n"
"| 2 | **Try-On Module (TOM)** | U-Net synthesis + soft composition mask + VGG perceptual loss |\n\n"
"Key CV techniques: convolutional feature pyramids, cross-correlation matching,\n"
"Thin Plate Spline (TPS) warping, U-Net encoder-decoder with skip connections,\n"
"composition mask, VGG-16 perceptual loss (relu1_2, relu2_2, relu3_3)."
))

# ── 2 · TOC ───────────────────────────────────────────────────────────────────
C.append(md(
"## Table of Contents\n"
"1. [Setup & Configuration](#1)\n"
"2. [Exploratory Data Analysis](#2)\n"
"3. [Dataset & Data Pipeline](#3)\n"
"4. [Architecture](#4)\n"
"   - 4.1 TPS Grid Generator\n   - 4.2 Geometric Matching Module (GMM)\n"
"   - 4.3 Try-On Module (TOM)\n   - 4.4 VGG Perceptual Loss\n"
"5. [Stage 1 — GMM Training](#5)\n"
"6. [Stage 2 — TOM Training](#6)\n"
"7. [Results](#7)\n"
"8. [Overfitting Analysis](#8)\n"
"9. [Conclusion & References](#9)\n"
))

# ── 2b · Dataset download cell ────────────────────────────────────────────────
C.append(md(
"## 0. Dataset Setup\n\n"
"Checks for the VITON-HD dataset locally. Downloads from Kaggle only if missing.\n\n"
"> **Colab users**: if prompted, enter your [Kaggle API credentials](https://www.kaggle.com/settings/account) "
"(username + API key from `kaggle.json`)."
))
C.append(code(
"import zipfile, subprocess\n"
"from pathlib import Path\n\n"
"DATASET_DIR = Path('./dataset')\n"
"ZIP_PATH    = DATASET_DIR / 'complete dataset.zip'\n"
"KAGGLE_URL  = 'https://www.kaggle.com/api/v1/datasets/download/marquis03/high-resolution-viton-zalando-dataset'\n\n"
"def dataset_ready():\n"
"    p = DATASET_DIR / 'train' / 'image'\n"
"    return p.exists() and len(list(p.iterdir())) > 100\n\n"
"if dataset_ready():\n"
"    print('Dataset already present — skipping download.')\n"
"else:\n"
"    DATASET_DIR.mkdir(exist_ok=True)\n\n"
"    if not ZIP_PATH.exists():\n"
"        print('Downloading dataset (~4.4 GB) ...')\n"
"        subprocess.run(\n"
"            ['curl', '-L', '-o', str(ZIP_PATH), KAGGLE_URL],\n"
"            check=True\n"
"        )\n"
"        print('Download complete.')\n"
"    else:\n"
"        print(f'Zip already at {ZIP_PATH} — skipping download.')\n\n"
"    print('Extracting ...')\n"
"    with zipfile.ZipFile(ZIP_PATH, 'r') as z:\n"
"        z.extractall(DATASET_DIR)\n"
"    print('Done.')\n"
"    print(f'Train images : {len(list((DATASET_DIR/\"train\"/\"image\").iterdir())):,}')\n"
"    print(f'Test  images : {len(list((DATASET_DIR/\"test\" /\"image\").iterdir())):,}')\n"
))

# ── 3 · Setup ─────────────────────────────────────────────────────────────────
C.append(md("## 1. Setup & Configuration <a id='1'></a>"))
C.append(code(
"import os, json, random, time, warnings\n"
"import numpy as np\n"
"import pandas as pd\n"
"import matplotlib.pyplot as plt\n"
"import matplotlib.patches as mpatches\n"
"import seaborn as sns\n"
"from PIL import Image\n"
"import cv2\n"
"from pathlib import Path\n"
"from collections import Counter\n\n"
"import torch\n"
"import torch.nn as nn\n"
"import torch.nn.functional as F\n"
"from torch.utils.data import Dataset, DataLoader\n"
"import torchvision.transforms as T\n"
"import torchvision.transforms.functional as TF\n"
"from torchvision.models import vgg16, VGG16_Weights\n"
"from skimage.metrics import structural_similarity as ssim\n"
"from skimage.metrics import peak_signal_noise_ratio as psnr\n\n"
"warnings.filterwarnings('ignore')\n\n"
"# Reproducibility\n"
"SEED = 42\n"
"random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)\n\n"
"# Paths\n"
"BASE_DIR  = Path('./dataset')\n"
"TRAIN_DIR = BASE_DIR / 'train'\n"
"TEST_DIR  = BASE_DIR / 'test'\n\n"
"# Hyperparameters\n"
"IMG_H, IMG_W  = 256, 192\n"
"BATCH_SIZE    = 4\n"
"GMM_EPOCHS    = 20\n"
"TOM_EPOCHS    = 20\n"
"LR            = 2e-4\n"
"WEIGHT_DECAY  = 1e-4\n"
"PATIENCE      = 5\n"
"N_TRAIN       = 600\n"
"N_VAL         = 100\n"
"N_CTRL        = 5\n"
"DEVICE        = torch.device('cpu')\n"
"CLOTH_LABEL   = 5\n\n"
"LABEL_NAMES = {\n"
"    0:'Background',1:'Hat',2:'Hair',3:'Sunglasses',4:'Upper-cloth',\n"
"    5:'Dress/Upper',6:'Coat',7:'Socks',8:'Pants',9:'Right Shoe',\n"
"    10:'Left Shoe',11:'Face',12:'Left Leg',13:'Right Leg',\n"
"    14:'Left Arm',15:'Right Arm',16:'Bag',17:'Scarf',\n"
"}\n\n"
"print(f'PyTorch {torch.__version__} | Device: {DEVICE}')\n"
"print(f'Image size : {IMG_H}x{IMG_W} | Batch: {BATCH_SIZE}')\n"
"print(f'TPS ctrl pts: {N_CTRL}x{N_CTRL}={N_CTRL**2} | Train/Val: {N_TRAIN}/{N_VAL}')\n"
))

# ── 4 · EDA header ────────────────────────────────────────────────────────────
C.append(md("## 2. Exploratory Data Analysis <a id='2'></a>"))

# ── 5 · Load pairs ────────────────────────────────────────────────────────────
C.append(code(
"def load_pairs(fp):\n"
"    pairs = []\n"
"    with open(fp) as f:\n"
"        for line in f:\n"
"            p = line.strip().split()\n"
"            if len(p) == 2: pairs.append((p[0], p[1]))\n"
"    return pairs\n\n"
"train_pairs = load_pairs(BASE_DIR / 'train_pairs.txt')\n"
"test_pairs  = load_pairs(BASE_DIR / 'test_pairs.txt')\n"
"random.shuffle(train_pairs)\n\n"
"print(f'Train pairs: {len(train_pairs):,}  |  Test pairs: {len(test_pairs):,}')\n"
"print(f'Sample train pair: {train_pairs[0]}')\n\n"
"modalities = sorted([d for d in os.listdir(TRAIN_DIR) if (TRAIN_DIR/d).is_dir()])\n"
"print(f'\\nModalities ({len(modalities)}):')\n"
"for m in modalities:\n"
"    n = len(list((TRAIN_DIR/m).iterdir()))\n"
"    print(f'  {m:35s} {n:>6,} files')\n"
))

# ── 6 · Sample visualisation ──────────────────────────────────────────────────
C.append(md("### 2.1 Sample Pair Visualisation\nFive modalities used by the pipeline for 3 random training pairs."))
C.append(code(
"PARSE_PALETTE = np.array([\n"
"    [0,0,0],[128,0,0],[255,0,0],[0,85,0],[170,0,51],\n"
"    [255,85,0],[0,0,85],[0,119,221],[85,85,0],[0,85,85],\n"
"    [85,51,0],[52,86,128],[0,128,0],[0,0,255],[51,170,221],\n"
"    [0,255,255],[85,255,170],[170,255,85],[255,255,0],[255,170,0]\n"
"], dtype=np.uint8)\n\n"
"def colorize_parse(arr):\n"
"    rgb = np.zeros((*arr.shape, 3), dtype=np.uint8)\n"
"    for lbl, col in enumerate(PARSE_PALETTE):\n"
"        if lbl < len(PARSE_PALETTE): rgb[arr==lbl] = col\n"
"    return rgb\n\n"
"N_SHOW = 3\n"
"fig, axes = plt.subplots(N_SHOW, 5, figsize=(18, 4.5*N_SHOW))\n"
"fig.suptitle('Dataset Sample Pairs', fontsize=14, fontweight='bold', y=1.01)\n"
"titles = ['Person Image','Target Cloth','Cloth Mask','Parse Map','Agnostic']\n\n"
"for row, idx in enumerate(random.sample(range(len(train_pairs)), N_SHOW)):\n"
"    pname, cname = train_pairs[idx]\n"
"    base = pname.replace('.jpg','')\n"
"    imgs = [\n"
"        np.array(Image.open(TRAIN_DIR/'image'/pname)),\n"
"        np.array(Image.open(TRAIN_DIR/'cloth'/cname)),\n"
"        np.array(Image.open(TRAIN_DIR/'cloth-mask'/cname).convert('L')),\n"
"        colorize_parse(np.array(Image.open(TRAIN_DIR/'image-parse-v3'/(base+'.png')))),\n"
"        np.array(Image.open(TRAIN_DIR/'agnostic-v3.2'/pname)),\n"
"    ]\n"
"    cmaps = [None, None, 'gray', None, None]\n"
"    for col,(img,cm,title) in enumerate(zip(imgs,cmaps,titles)):\n"
"        axes[row][col].imshow(img, cmap=cm)\n"
"        axes[row][col].axis('off')\n"
"        if row==0: axes[row][col].set_title(title, fontsize=10, fontweight='bold')\n"
"    axes[row][0].set_ylabel(f'Pair {row+1}', fontsize=10)\n\n"
"plt.tight_layout(); plt.show()\n"
))

# ── 7 · Parse label distribution ─────────────────────────────────────────────
C.append(md("### 2.2 Parse-Map Label Distribution\nLabel 5 (red) is the upper-clothing region used as GMM supervision."))
C.append(code(
"N = 60\n"
"lcount = Counter()\n"
"for pname, _ in random.sample(train_pairs, N):\n"
"    parse = np.array(Image.open(TRAIN_DIR/'image-parse-v3'/(pname.replace('.jpg','')+'.png')))\n"
"    for lbl in np.unique(parse):\n"
"        lcount[int(lbl)] += int((parse==lbl).sum())\n\n"
"labels = sorted(lcount.keys())\n"
"names  = [LABEL_NAMES.get(l, f'L{l}') for l in labels]\n"
"counts = [lcount[l] for l in labels]\n"
"colors = ['#e74c3c' if l==CLOTH_LABEL else '#3498db' for l in labels]\n\n"
"fig, ax = plt.subplots(figsize=(13,4))\n"
"ax.bar(names, [c/1e6 for c in counts], color=colors, edgecolor='white')\n"
"ax.set_ylabel('Pixel count (M)'); ax.set_title('Parse-Map Label Distribution (60 images)')\n"
"plt.xticks(rotation=45, ha='right', fontsize=9); ax.grid(axis='y', alpha=0.3)\n"
"ax.legend(handles=[\n"
"    mpatches.Patch(color='#e74c3c', label=f'Clothing label {CLOTH_LABEL} — GMM target'),\n"
"    mpatches.Patch(color='#3498db', label='Other labels')\n"
"], fontsize=10)\n"
"plt.tight_layout(); plt.show()\n"
"pct = lcount[CLOTH_LABEL]/sum(lcount.values())*100\n"
"print(f'Cloth label occupies {pct:.1f}% of pixels')\n"
))

# ── 8 · Image stats ───────────────────────────────────────────────────────────
C.append(md("### 2.3 Image Statistics & Cloth-Mask Coverage"))
C.append(code(
"N = 60; pb, cb, cov = [], [], []\n"
"for pname, cname in random.sample(train_pairs, N):\n"
"    pb.append(np.array(Image.open(TRAIN_DIR/'image'/pname).convert('RGB')).mean())\n"
"    cb.append(np.array(Image.open(TRAIN_DIR/'cloth'/cname).convert('RGB')).mean())\n"
"    mask = np.array(Image.open(TRAIN_DIR/'cloth-mask'/cname).convert('L'))\n"
"    cov.append((mask>127).mean()*100)\n\n"
"print(f'Person brightness: {np.mean(pb):.1f} +/- {np.std(pb):.1f}')\n"
"print(f'Cloth  brightness: {np.mean(cb):.1f} +/- {np.std(cb):.1f}')\n"
"print(f'Cloth mask coverage: {np.mean(cov):.1f}% +/- {np.std(cov):.1f}%')\n"
"print(f'Original resolution: 768x1024  ->  resized to {IMG_W}x{IMG_H} for training')\n\n"
"fig, axes = plt.subplots(1,3,figsize=(15,4))\n"
"axes[0].hist(pb,bins=20,color='steelblue',alpha=0.7,label='Person')\n"
"axes[0].hist(cb,bins=20,color='salmon',alpha=0.7,label='Cloth')\n"
"axes[0].set_title('Brightness Distribution'); axes[0].legend(); axes[0].grid(alpha=0.3)\n"
"axes[1].boxplot([pb,cb],labels=['Person','Cloth'])\n"
"axes[1].set_title('Brightness Boxplot'); axes[1].grid(alpha=0.3)\n"
"axes[2].hist(cov,bins=20,color='mediumseagreen',edgecolor='white')\n"
"axes[2].axvline(np.mean(cov),color='red',ls='--',label=f'Mean={np.mean(cov):.1f}%')\n"
"axes[2].set_title('Cloth-Mask Coverage (%)'); axes[2].legend(); axes[2].grid(alpha=0.3)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── 9 · Keypoint analysis ────────────────────────────────────────────────────
C.append(md("### 2.4 OpenPose Keypoint Analysis\nBODY_25 keypoints (25 pts). Upper-body points guide GMM cloth alignment."))
C.append(code(
"KP_NAMES = {0:'Nose',1:'Neck',2:'RShoulder',3:'RElbow',4:'RWrist',\n"
"            5:'LShoulder',6:'LElbow',7:'LWrist',8:'MidHip',\n"
"            9:'RHip',10:'RKnee',11:'RAnkle',12:'LHip',13:'LKnee',14:'LAnkle'}\n"
"UPPER_KP = [1,2,5,8,9,12]\n\n"
"kp_conf = {k:[] for k in range(15)}\n"
"kp_px   = {k:[] for k in range(15)}\n"
"kp_py   = {k:[] for k in range(15)}\n\n"
"for pname,_ in random.sample(train_pairs, 60):\n"
"    jf = TRAIN_DIR/'openpose_json'/(pname.replace('.jpg','')+'_keypoints.json')\n"
"    if not jf.exists(): continue\n"
"    with open(jf) as f: data=json.load(f)\n"
"    if not data['people']: continue\n"
"    kps = data['people'][0]['pose_keypoints_2d']\n"
"    for k in range(15):\n"
"        x,y,c = kps[k*3],kps[k*3+1],kps[k*3+2]\n"
"        if c>0.1:\n"
"            kp_conf[k].append(c); kp_px[k].append(x/768); kp_py[k].append(y/1024)\n\n"
"fig, axes = plt.subplots(1,2,figsize=(14,5))\n"
"fig.suptitle('OpenPose BODY_25 — Upper-Body Keypoints', fontsize=13, fontweight='bold')\n\n"
"axes[0].boxplot([kp_conf[k] for k in UPPER_KP],\n"
"                labels=[KP_NAMES[k] for k in UPPER_KP],\n"
"                patch_artist=True, boxprops=dict(facecolor='skyblue'))\n"
"axes[0].set_title('Confidence Scores'); axes[0].set_ylabel('Confidence'); axes[0].grid(alpha=0.3)\n\n"
"for k in UPPER_KP:\n"
"    if kp_px[k]:\n"
"        mx,my = np.mean(kp_px[k]),np.mean(kp_py[k])\n"
"        axes[1].scatter(mx,my,s=120,zorder=5)\n"
"        axes[1].annotate(KP_NAMES[k],(mx,my),xytext=(5,5),textcoords='offset points',fontsize=9)\n"
"axes[1].set_xlim(0,1); axes[1].set_ylim(0,1); axes[1].invert_yaxis()\n"
"axes[1].set_title('Mean Normalised Positions')\n"
"axes[1].set_xlabel('x'); axes[1].set_ylabel('y'); axes[1].grid(alpha=0.3)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── 10 · Dataset class ────────────────────────────────────────────────────────
C.append(md("## 3. Dataset & Data Pipeline <a id='3'></a>"))
C.append(code(
"class VTONDataset(Dataset):\n"
"    # Loads: person, cloth, cloth_mask, agnostic, parse, cloth_region\n"
"    # person / cloth / agnostic : (3,H,W) normalised to [-1,1]\n"
"    # cloth_mask / cloth_region : (1,H,W) binary [0,1]\n"
"    # parse                     : (H,W)   long label map\n\n"
"    def __init__(self, pairs, base_dir, img_h=256, img_w=192, augment=False):\n"
"        self.pairs=pairs; self.base_dir=Path(base_dir)\n"
"        self.img_h=img_h; self.img_w=img_w; self.augment=augment\n"
"        self.img_tf = T.Compose([\n"
"            T.Resize((img_h,img_w)), T.ToTensor(),\n"
"            T.Normalize([0.5]*3,[0.5]*3)\n"
"        ])\n\n"
"    def __len__(self): return len(self.pairs)\n\n"
"    def __getitem__(self, idx):\n"
"        pname, cname = self.pairs[idx]\n"
"        base = pname.replace('.jpg','')\n"
"        person   = Image.open(self.base_dir/'image'/pname).convert('RGB')\n"
"        cloth    = Image.open(self.base_dir/'cloth'/cname).convert('RGB')\n"
"        c_mask   = Image.open(self.base_dir/'cloth-mask'/cname).convert('L')\n"
"        agnostic = Image.open(self.base_dir/'agnostic-v3.2'/pname).convert('RGB')\n"
"        parse_np = np.array(Image.open(self.base_dir/'image-parse-v3'/(base+'.png')))\n\n"
"        if self.augment and random.random()>0.5:\n"
"            person=TF.hflip(person); cloth=TF.hflip(cloth)\n"
"            c_mask=TF.hflip(c_mask); agnostic=TF.hflip(agnostic)\n"
"            parse_np=np.fliplr(parse_np).copy()\n\n"
"        person_t  = self.img_tf(person)\n"
"        cloth_t   = self.img_tf(cloth)\n"
"        agno_t    = self.img_tf(agnostic)\n\n"
"        cm_arr = np.array(c_mask.resize((self.img_w,self.img_h),Image.NEAREST))\n"
"        cm_t   = torch.from_numpy((cm_arr>127).astype(np.float32)).unsqueeze(0)\n\n"
"        ps = cv2.resize(parse_np,(self.img_w,self.img_h),interpolation=cv2.INTER_NEAREST)\n"
"        parse_t = torch.from_numpy(ps).long()\n"
"        cr_t    = torch.from_numpy((ps==CLOTH_LABEL).astype(np.float32)).unsqueeze(0)\n\n"
"        return dict(person=person_t, cloth=cloth_t, cloth_mask=cm_t,\n"
"                    agnostic=agno_t, parse=parse_t, cloth_region=cr_t)\n\n\n"
"tr_pairs  = train_pairs[:N_TRAIN]\n"
"val_pairs = train_pairs[N_TRAIN:N_TRAIN+N_VAL]\n\n"
"train_ds = VTONDataset(tr_pairs,  TRAIN_DIR, IMG_H, IMG_W, augment=True)\n"
"val_ds   = VTONDataset(val_pairs, TRAIN_DIR, IMG_H, IMG_W, augment=False)\n"
"test_ds  = VTONDataset(test_pairs[:100], TEST_DIR, IMG_H, IMG_W, augment=False)\n\n"
"train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=0)\n"
"val_dl   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0)\n"
"test_dl  = DataLoader(test_ds,  batch_size=4,          shuffle=False, num_workers=0)\n\n"
"print(f'Train batches:{len(train_dl)} | Val:{len(val_dl)} | Test:{len(test_dl)}')\n"
"s = train_ds[0]\n"
"for k,v in s.items(): print(f'  {k:14s} shape={tuple(v.shape)} dtype={v.dtype}')\n"
))

# ── 11 · Architecture header ──────────────────────────────────────────────────
C.append(md(
"## 4. Architecture <a id='4'></a>\n\n"
"```\n"
"Input: agnostic person image + target garment\n\n"
"Stage 1 — Geometric Matching Module (GMM)\n"
"  agnostic  ->  FeatureExtractor  ->\n"
"                                    CorrelationLayer  ->\n"
"  cloth     ->  FeatureExtractor  ->               Conv Regressor\n"
"                                                          |\n"
"                                               theta (2 x 25 TPS params)\n"
"                                                          |\n"
"                                              TPS Grid Generator\n"
"                                                          |\n"
"  cloth  ----------------------->  F.grid_sample  ->  warped_cloth\n\n"
"Stage 2 — Try-On Module (TOM)\n"
"  [agnostic | warped_cloth | warped_mask]  (7 channels)\n"
"              U-Net Encoder-Decoder\n"
"          /                       \\\n"
"    rendered (3ch)           mask (1ch)\n"
"          \\                       /\n"
"   output = mask * warped_cloth + (1-mask) * rendered\n"
"```\n"
))

# ── 12 · TPS grid generator ───────────────────────────────────────────────────
C.append(md("### 4.1 Thin Plate Spline (TPS) Grid Generator\n"
            "Implements the TPS basis U(r) = r² log(r²) to compute a dense backward-warp grid from predicted control-point offsets."))
C.append(code(
"class TPSWarp(nn.Module):\n"
"    # Thin Plate Spline warping.\n"
"    # theta : (B, 2, N) offsets for NxN control points\n"
"    # returns: sampling grid (B, H, W, 2) for F.grid_sample\n\n"
"    def __init__(self, img_h=256, img_w=192, n_ctrl=5):\n"
"        super().__init__()\n"
"        self.img_h=img_h; self.img_w=img_w\n"
"        self.N = n_ctrl*n_ctrl\n\n"
"        cx = torch.linspace(-1,1,n_ctrl)\n"
"        cy = torch.linspace(-1,1,n_ctrl)\n"
"        gy,gx = torch.meshgrid(cy,cx,indexing='ij')\n"
"        ctrl  = torch.stack([gx.flatten(),gy.flatten()],dim=1)  # (N,2)\n"
"        self.register_buffer('ctrl_src', ctrl)\n\n"
"        ox = torch.linspace(-1,1,img_w)\n"
"        oy = torch.linspace(-1,1,img_h)\n"
"        ogy,ogx = torch.meshgrid(oy,ox,indexing='ij')\n"
"        out_pts = torch.stack([ogx.flatten(),ogy.flatten()],dim=1)  # (H*W,2)\n"
"        self.register_buffer('out_pts', out_pts)\n\n"
"    @staticmethod\n"
"    def _U(r2):\n"
"        r2 = r2.clamp(min=1e-10)\n"
"        return r2 * torch.log(r2)\n\n"
"    @staticmethod\n"
"    def _K(a, b):\n"
"        diff = a.unsqueeze(1)-b.unsqueeze(0)   # (n,m,2)\n"
"        return TPSWarp._U((diff**2).sum(-1))   # (n,m)\n\n"
"    def forward(self, theta):\n"
"        B,_,N = theta.shape\n"
"        dev   = theta.device\n"
"        ctrl_src = self.ctrl_src.to(dev)\n"
"        ctrl_tgt = ctrl_src.unsqueeze(0) + theta.permute(0,2,1)  # (B,N,2)\n"
"        out_pts  = self.out_pts.to(dev)\n"
"        HW = out_pts.shape[0]\n\n"
"        grids = []\n"
"        for b in range(B):\n"
"            C_t = ctrl_tgt[b]          # (N,2) target positions\n"
"            C_s = ctrl_src             # (N,2) source values\n"
"            K   = self._K(C_t,C_t) + 1e-6*torch.eye(N,device=dev)\n"
"            ones = torch.ones(N,1,device=dev)\n"
"            P    = torch.cat([ones,C_t],dim=1)   # (N,3)\n"
"            L    = torch.cat([\n"
"                torch.cat([K,P],dim=1),\n"
"                torch.cat([P.t(),torch.zeros(3,3,device=dev)],dim=1)\n"
"            ],dim=0)                             # (N+3,N+3)\n"
"            try:\n"
"                wx = torch.linalg.solve(L, torch.cat([C_s[:,0],torch.zeros(3,device=dev)]))\n"
"                wy = torch.linalg.solve(L, torch.cat([C_s[:,1],torch.zeros(3,device=dev)]))\n"
"            except Exception:\n"
"                grids.append(torch.stack([out_pts[:,0],out_pts[:,1]],dim=-1))\n"
"                continue\n"
"            Phi   = self._K(out_pts,C_t)\n"
"            P_out = torch.cat([torch.ones(HW,1,device=dev),out_pts],dim=1)  # (HW,3)\n"
"            basis = torch.cat([Phi,P_out],dim=1)  # (HW,N+3)\n"
"            grids.append(torch.stack([basis@wx, basis@wy],dim=-1))\n\n"
"        grid = torch.stack(grids,dim=0).reshape(B,self.img_h,self.img_w,2)\n"
"        return grid.clamp(-1,1)\n\n\n"
"# Unit test\n"
"_tps   = TPSWarp(IMG_H, IMG_W, N_CTRL)\n"
"_theta = torch.zeros(2, 2, N_CTRL**2)\n"
"_grid  = _tps(_theta)\n"
"_warp  = F.grid_sample(torch.randn(2,3,IMG_H,IMG_W),_grid,align_corners=True)\n"
"print(f'TPS unit test OK -> grid {tuple(_grid.shape)}, warped {tuple(_warp.shape)}')\n"
))

# ── 13 · GMM ──────────────────────────────────────────────────────────────────
C.append(md("### 4.2 Geometric Matching Module (GMM)\n"
            "CNN feature extraction + cross-correlation + TPS regression."))
C.append(code(
"class FeatureExtractor(nn.Module):\n"
"    # 3-layer CNN -> (B, 64, H/8, W/8) feature maps\n"
"    def __init__(self, in_ch=3, out_ch=64):\n"
"        super().__init__()\n"
"        self.net = nn.Sequential(\n"
"            nn.Conv2d(in_ch,32,3,padding=1,bias=False), nn.BatchNorm2d(32), nn.ReLU(True), nn.MaxPool2d(2),\n"
"            nn.Conv2d(32,64,3,padding=1,bias=False),    nn.BatchNorm2d(64), nn.ReLU(True), nn.MaxPool2d(2),\n"
"            nn.Conv2d(64,out_ch,3,padding=1,bias=False),nn.BatchNorm2d(out_ch),nn.ReLU(True),nn.MaxPool2d(2),\n"
"        )\n"
"    def forward(self,x): return self.net(x)\n\n\n"
"class CorrelationLayer(nn.Module):\n"
"    # Cross-correlation: (B,C,H,W)x2 -> (B, H*W, H, W)\n"
"    # Each output channel = dot product with one reference feature vector\n"
"    def forward(self,fa,fb):\n"
"        B,C,H,W = fa.shape\n"
"        fa_n = F.normalize(fa.view(B,C,-1),dim=1)  # (B,C,HW)\n"
"        fb_n = F.normalize(fb.view(B,C,-1),dim=1)\n"
"        corr = torch.bmm(fa_n.permute(0,2,1),fb_n)  # (B,HW,HW)\n"
"        return corr.view(B,H*W,H,W)\n\n\n"
"class GMM(nn.Module):\n"
"    # Geometric Matching Module (CP-VTON style):\n"
"    #   agnostic + cloth -> FeatureExtractor -> CorrelationLayer\n"
"    #   -> regressor -> theta (TPS offsets) -> TPSWarp -> warped cloth/mask\n\n"
"    def __init__(self, n_ctrl=5, img_h=256, img_w=192):\n"
"        super().__init__()\n"
"        self.N = n_ctrl*n_ctrl\n"
"        fh,fw = img_h//8, img_w//8  # feature map size: 32x24\n"
"        corr_ch = fh*fw             # 768 correlation channels\n\n"
"        self.feat_p = FeatureExtractor(3, 64)\n"
"        self.feat_c = FeatureExtractor(3, 64)\n"
"        self.corr   = CorrelationLayer()\n\n"
"        self.reg = nn.Sequential(\n"
"            nn.Conv2d(corr_ch,128,3,padding=1), nn.ReLU(True), nn.MaxPool2d(2),\n"
"            nn.Conv2d(128,64,3,padding=1),      nn.ReLU(True), nn.AdaptiveAvgPool2d((4,4)),\n"
"            nn.Flatten(),\n"
"            nn.Linear(64*16,256), nn.ReLU(True), nn.Dropout(0.5),\n"
"            nn.Linear(256, 2*self.N), nn.Tanh(),\n"
"        )\n"
"        self.tps   = TPSWarp(img_h, img_w, n_ctrl)\n"
"        self.scale = 0.4\n\n"
"    def forward(self, agnostic, cloth, cloth_mask):\n"
"        corr  = self.corr(self.feat_p(agnostic), self.feat_c(cloth))\n"
"        theta = (self.reg(corr)*self.scale).view(-1,2,self.N)\n"
"        grid         = self.tps(theta)\n"
"        warped_cloth = F.grid_sample(cloth,      grid, mode='bilinear', padding_mode='border', align_corners=True)\n"
"        warped_mask  = F.grid_sample(cloth_mask, grid, mode='bilinear', padding_mode='zeros',  align_corners=True)\n"
"        return warped_cloth, warped_mask, theta\n\n\n"
"gmm   = GMM(n_ctrl=N_CTRL, img_h=IMG_H, img_w=IMG_W).to(DEVICE)\n"
"p_gmm = sum(p.numel() for p in gmm.parameters() if p.requires_grad)\n"
"print(f'GMM parameters: {p_gmm:,}')\n"
"_b  = next(iter(train_dl))\n"
"_wc,_wm,_th = gmm(_b['agnostic'],_b['cloth'],_b['cloth_mask'])\n"
"print(f'GMM -> warped_cloth {tuple(_wc.shape)}, warped_mask {tuple(_wm.shape)}, theta {tuple(_th.shape)}')\n"
))

# ── 14 · TOM ──────────────────────────────────────────────────────────────────
C.append(md("### 4.3 Try-On Module (TOM)\nU-Net with dual output head: rendered image + soft composition mask."))
C.append(code(
"class ConvBlock(nn.Module):\n"
"    def __init__(self,ic,oc,drop=0.1):\n"
"        super().__init__()\n"
"        self.b = nn.Sequential(\n"
"            nn.Conv2d(ic,oc,3,padding=1,bias=False),nn.BatchNorm2d(oc),nn.ReLU(True),\n"
"            nn.Conv2d(oc,oc,3,padding=1,bias=False),nn.BatchNorm2d(oc),nn.ReLU(True),\n"
"            nn.Dropout2d(drop),\n"
"        )\n"
"    def forward(self,x): return self.b(x)\n\n\n"
"class TOM(nn.Module):\n"
"    # U-Net: 7ch [agnostic|warped_cloth|warped_mask] -> rendered(3ch) + mask(1ch)\n"
"    # Final: output = mask * warped_cloth + (1-mask) * rendered\n\n"
"    def __init__(self, in_ch=7, features=(32,64,128)):\n"
"        super().__init__()\n"
"        f = list(features)\n"
"        self.pool = nn.MaxPool2d(2)\n"
"        self.e1=ConvBlock(in_ch,f[0],0.1); self.e2=ConvBlock(f[0],f[1],0.2)\n"
"        self.e3=ConvBlock(f[1],f[2],0.3); self.bt=ConvBlock(f[2],f[2]*2,0.3)\n"
"        self.u3=nn.ConvTranspose2d(f[2]*2,f[2],2,2); self.d3=ConvBlock(f[2]*2,f[2],0.2)\n"
"        self.u2=nn.ConvTranspose2d(f[2],f[1],2,2);   self.d2=ConvBlock(f[1]*2,f[1],0.1)\n"
"        self.u1=nn.ConvTranspose2d(f[1],f[0],2,2);   self.d1=ConvBlock(f[0]*2,f[0])\n"
"        self.rh = nn.Sequential(nn.Conv2d(f[0],3,1),nn.Tanh())\n"
"        self.mh = nn.Sequential(nn.Conv2d(f[0],1,1),nn.Sigmoid())\n"
"        self._init()\n\n"
"    def _init(self):\n"
"        for m in self.modules():\n"
"            if isinstance(m,nn.Conv2d): nn.init.kaiming_normal_(m.weight,nonlinearity='relu')\n"
"            elif isinstance(m,nn.BatchNorm2d): nn.init.constant_(m.weight,1); nn.init.constant_(m.bias,0)\n\n"
"    def forward(self,x,warped_cloth):\n"
"        e1=self.e1(x); e2=self.e2(self.pool(e1)); e3=self.e3(self.pool(e2))\n"
"        bt=self.bt(self.pool(e3))\n"
"        d3=self.d3(torch.cat([self.u3(bt),e3],1))\n"
"        d2=self.d2(torch.cat([self.u2(d3),e2],1))\n"
"        d1=self.d1(torch.cat([self.u1(d2),e1],1))\n"
"        rendered=self.rh(d1); mask=self.mh(d1)\n"
"        return mask*warped_cloth+(1-mask)*rendered, rendered, mask\n\n\n"
"tom   = TOM(in_ch=7).to(DEVICE)\n"
"p_tom = sum(p.numel() for p in tom.parameters() if p.requires_grad)\n"
"print(f'TOM parameters: {p_tom:,}')\n"
"_xi = torch.cat([_b['agnostic'],_wc.detach(),_wm.detach()],dim=1)\n"
"_out,_ren,_msk = tom(_xi,_wc.detach())\n"
"print(f'TOM -> output {tuple(_out.shape)}, mask {tuple(_msk.shape)}')\n"
))

# ── 15 · VGG loss ─────────────────────────────────────────────────────────────
C.append(md("### 4.4 VGG-16 Perceptual Loss\n"
            "Pretrained VGG-16 features (relu1_2, relu2_2, relu3_3) measure semantic/texture similarity.\n"
            "VGG weights are **frozen** — only used for loss computation."))
C.append(code(
"class VGGPerceptualLoss(nn.Module):\n"
"    # Feature layers: relu1_2 (w=1.0), relu2_2 (w=0.75), relu3_3 (w=0.5)\n"
"    # Input: images in [-1,1]; converts to VGG-normalised [0,1] internally\n\n"
"    def __init__(self):\n"
"        super().__init__()\n"
"        feats  = list(vgg16(weights=VGG16_Weights.DEFAULT).features)\n"
"        self.s1 = nn.Sequential(*feats[:5])    # relu1_2\n"
"        self.s2 = nn.Sequential(*feats[5:10])  # relu2_2\n"
"        self.s3 = nn.Sequential(*feats[10:17]) # relu3_3\n"
"        for p in self.parameters(): p.requires_grad=False\n"
"        self.register_buffer('mean',torch.tensor([0.485,0.456,0.406]).view(1,3,1,1))\n"
"        self.register_buffer('std', torch.tensor([0.229,0.224,0.225]).view(1,3,1,1))\n\n"
"    def _prep(self,x):\n"
"        return ((x*0.5+0.5)-self.mean)/self.std\n\n"
"    def forward(self,pred,target):\n"
"        p=self._prep(pred); t=self._prep(target)\n"
"        loss=0.0\n"
"        for sl,w in zip([self.s1,self.s2,self.s3],[1.0,0.75,0.5]):\n"
"            p=sl(p); t=sl(t)\n"
"            loss = loss + w*F.l1_loss(p,t)\n"
"        return loss\n\n\n"
"vgg_loss = VGGPerceptualLoss().to(DEVICE)\n"
"_pl = vgg_loss(_out.detach(), _b['person'])\n"
"print(f'VGG perceptual loss test: {_pl.item():.4f}  OK')\n"
"print(f'\\n{\"Component\":20s} {\"Params\":>12s}')\n"
"print('-'*35)\n"
"print(f'{\"GMM\":20s} {p_gmm:>12,}')\n"
"print(f'{\"TOM\":20s} {p_tom:>12,}')\n"
"print(f'{\"VGG (frozen)\":20s} {\"no grad\":>12s}')\n"
"print(f'{\"Total trainable\":20s} {p_gmm+p_tom:>12,}')\n"
))

# ── 16 · GMM training ────────────────────────────────────────────────────────
C.append(md(
"## 5. Stage 1 — GMM Training (Cloth Warping) <a id='5'></a>\n\n"
"**Loss**: L1(warped_mask, cloth_region) + 0.01 × L2(theta)\n\n"
"L1 alignment forces the warped cloth mask to cover the person's clothing region.\n"
"L2 on theta regularises the TPS offsets, preventing degenerate warps."
))
C.append(code(
"gmm_opt = torch.optim.Adam(gmm.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)\n"
"gmm_sch = torch.optim.lr_scheduler.ReduceLROnPlateau(gmm_opt,'min',factor=0.5,patience=3)\n\n"
"def gmm_loss_fn(wm, cr, theta, rw=0.01):\n"
"    mask_l = F.l1_loss(wm, cr)\n"
"    reg_l  = (theta**2).mean()\n"
"    return mask_l + rw*reg_l, mask_l, reg_l\n\n\n"
"def gmm_epoch(model, dl, opt, train):\n"
"    model.train(train)\n"
"    tot=ml=rl=0.0\n"
"    ctx = torch.enable_grad() if train else torch.no_grad()\n"
"    with ctx:\n"
"        for b in dl:\n"
"            wc,wm,th = model(b['agnostic'],b['cloth'],b['cloth_mask'])\n"
"            loss,ml_i,rl_i = gmm_loss_fn(wm,b['cloth_region'],th)\n"
"            if train:\n"
"                opt.zero_grad(); loss.backward()\n"
"                torch.nn.utils.clip_grad_norm_(model.parameters(),1.0); opt.step()\n"
"            tot+=loss.item(); ml+=ml_i.item(); rl+=rl_i.item()\n"
"    n=len(dl); return tot/n, ml/n, rl/n\n\n\n"
"gmm_h = {k:[] for k in ['tr','val','tr_m','val_m','lr']}\n"
"best_v=float('inf'); best_gmm_w=None; pat=0\n\n"
"print('Stage 1 — GMM Training'); print('='*72)\n"
"for ep in range(1,GMM_EPOCHS+1):\n"
"    t0=time.time()\n"
"    tr=gmm_epoch(gmm,train_dl,gmm_opt,True)\n"
"    va=gmm_epoch(gmm,val_dl,  gmm_opt,False)\n"
"    gmm_sch.step(va[0])\n"
"    lr=gmm_opt.param_groups[0]['lr']\n"
"    for k,v in zip(['tr','val','tr_m','val_m','lr'],[tr[0],va[0],tr[1],va[1],lr]):\n"
"        gmm_h[k].append(v)\n"
"    print(f'Ep{ep:2d}/{GMM_EPOCHS} | tr={tr[0]:.4f}(m={tr[1]:.4f},r={tr[2]:.4f}) | '\n"
"          f'val={va[0]:.4f}(m={va[1]:.4f}) | lr={lr:.6f} | {time.time()-t0:.1f}s')\n"
"    if va[0]<best_v:\n"
"        best_v=va[0]; pat=0\n"
"        best_gmm_w={k:v.cpu().clone() for k,v in gmm.state_dict().items()}\n"
"        print('   best GMM saved')\n"
"    else:\n"
"        pat+=1\n"
"        if pat>=PATIENCE: print(f'  Early stop ep{ep}'); break\n"
"gmm.load_state_dict(best_gmm_w)\n"
"print(f'GMM best val: {best_v:.4f}')\n"
))

# ── 17 · GMM curves ──────────────────────────────────────────────────────────
C.append(md("### 5.1 GMM Training Curves"))
C.append(code(
"ep=list(range(1,len(gmm_h['tr'])+1))\n"
"fig,axes=plt.subplots(1,3,figsize=(16,4))\n"
"fig.suptitle('GMM Training — Stage 1',fontsize=13,fontweight='bold')\n"
"axes[0].plot(ep,gmm_h['tr'],label='Train',color='steelblue',lw=2)\n"
"axes[0].plot(ep,gmm_h['val'],label='Val',color='darkorange',lw=2)\n"
"axes[0].set_title('Total Loss'); axes[0].legend(); axes[0].grid(alpha=0.3)\n"
"axes[1].plot(ep,gmm_h['tr_m'],label='Train',color='steelblue',lw=2)\n"
"axes[1].plot(ep,gmm_h['val_m'],label='Val',color='darkorange',lw=2)\n"
"axes[1].set_title('Mask Alignment (L1)'); axes[1].legend(); axes[1].grid(alpha=0.3)\n"
"axes[2].plot(ep,gmm_h['lr'],color='purple',lw=2)\n"
"axes[2].set_title('Learning Rate'); axes[2].set_yscale('log'); axes[2].grid(alpha=0.3)\n"
"for ax in axes: ax.set_xlabel('Epoch')\n"
"plt.tight_layout(); plt.savefig('gmm_training_curves.png',dpi=100,bbox_inches='tight'); plt.show()\n"
))

# ── 18 · GMM qualitative ─────────────────────────────────────────────────────
C.append(md("### 5.2 GMM Qualitative Results — TPS Cloth Warping"))
C.append(code(
"def denorm(t):\n"
"    return ((t*0.5+0.5).clamp(0,1).permute(1,2,0).detach().numpy()*255).astype(np.uint8)\n\n"
"gmm.eval()\n"
"N_SHOW=4\n"
"samples=[test_ds[i] for i in range(N_SHOW)]\n"
"batch={k:torch.stack([s[k] for s in samples]) for k in samples[0]}\n"
"with torch.no_grad():\n"
"    wc,wm,th=gmm(batch['agnostic'],batch['cloth'],batch['cloth_mask'])\n\n"
"col_titles=['Person (GT)','Target Cloth','Cloth Mask','Warped Cloth','Warp Overlay']\n"
"fig,axes=plt.subplots(N_SHOW,5,figsize=(19,4.8*N_SHOW))\n"
"fig.suptitle('GMM Results — TPS Cloth Warping',fontsize=14,fontweight='bold',y=1.01)\n"
"for row in range(N_SHOW):\n"
"    cr_np=batch['cloth_region'][row,0].numpy()\n"
"    wm_np=wm[row,0].detach().numpy()\n"
"    overlay=np.zeros((IMG_H,IMG_W,3),dtype=np.float32)\n"
"    overlay[...,0]=wm_np; overlay[...,1]=cr_np\n"
"    imgs=[denorm(batch['person'][row]),denorm(batch['cloth'][row]),\n"
"          batch['cloth_mask'][row,0].numpy(),denorm(wc[row]),overlay]\n"
"    cmaps=[None,None,'gray',None,None]\n"
"    for col,(img,cm,title) in enumerate(zip(imgs,cmaps,col_titles)):\n"
"        axes[row][col].imshow(img,cmap=cm,vmin=0 if cm else None,vmax=1 if cm else None)\n"
"        axes[row][col].axis('off')\n"
"        if row==0: axes[row][col].set_title(title,fontsize=10,fontweight='bold')\n"
"    axes[row][0].set_ylabel(f'Test {row+1}',fontsize=10)\n"
"fig.legend(handles=[\n"
"    mpatches.Patch(color='red',label='Warped mask (pred)'),\n"
"    mpatches.Patch(color='green',label='Cloth region (GT)')\n"
"],loc='lower center',ncol=2,fontsize=11)\n"
"plt.tight_layout(); plt.savefig('gmm_results.png',dpi=100,bbox_inches='tight'); plt.show()\n"
))

# ── 19 · TOM training ────────────────────────────────────────────────────────
C.append(md(
"## 6. Stage 2 — TOM Training (Try-On Synthesis) <a id='6'></a>\n\n"
"GMM weights are **frozen**. TOM learns to synthesise the final try-on image.\n\n"
"**Loss** = L1 pixel + 0.25 × VGG perceptual + 0.01 × mask TV regularisation\n\n"
"- **L1**: pixel-level accuracy\n"
"- **VGG perceptual**: preserves texture and semantic structure\n"
"- **Mask TV**: encourages a spatially smooth composition mask"
))
C.append(code(
"for p in gmm.parameters(): p.requires_grad=False\n\n"
"tom_opt = torch.optim.Adam(tom.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)\n"
"tom_sch = torch.optim.lr_scheduler.ReduceLROnPlateau(tom_opt,'min',factor=0.5,patience=3)\n"
"L1_FN   = nn.L1Loss()\n"
"VGG_W=0.25; MASK_TV_W=0.01\n\n"
"def tom_loss_fn(out, ren, mask, wc, target):\n"
"    l1   = L1_FN(out, target)\n"
"    perc = vgg_loss(out, target)\n"
"    tv   = (torch.abs(mask[:,:,1:,:]-mask[:,:,:-1,:]).mean() +\n"
"            torch.abs(mask[:,:,:,1:]-mask[:,:,:,:-1]).mean())\n"
"    return l1+VGG_W*perc+MASK_TV_W*tv, l1, perc, tv\n\n\n"
"def tom_epoch(gmm_m, tom_m, dl, opt, train):\n"
"    tom_m.train(train)\n"
"    tot=tl1=tpc=ttv=0.0\n"
"    ctx = torch.enable_grad() if train else torch.no_grad()\n"
"    with ctx:\n"
"        for b in dl:\n"
"            with torch.no_grad():\n"
"                wc,wm,_ = gmm_m(b['agnostic'],b['cloth'],b['cloth_mask'])\n"
"            xi  = torch.cat([b['agnostic'],wc,wm],dim=1)\n"
"            out,ren,msk = tom_m(xi,wc)\n"
"            loss,l1i,pci,tvi = tom_loss_fn(out,ren,msk,wc,b['person'])\n"
"            if train:\n"
"                opt.zero_grad(); loss.backward()\n"
"                torch.nn.utils.clip_grad_norm_(tom_m.parameters(),1.0); opt.step()\n"
"            tot+=loss.item(); tl1+=l1i.item(); tpc+=pci.item(); ttv+=tvi.item()\n"
"    n=len(dl); return tot/n,tl1/n,tpc/n,ttv/n\n\n\n"
"tom_h={k:[] for k in ['tr','val','tr_l1','val_l1','tr_pc','val_pc','lr']}\n"
"best_vt=float('inf'); best_tom_w=None; pat_t=0\n\n"
"print('Stage 2 — TOM Training  (GMM frozen)'); print('='*80)\n"
"for ep in range(1,TOM_EPOCHS+1):\n"
"    t0=time.time()\n"
"    tr=tom_epoch(gmm,tom,train_dl,tom_opt,True)\n"
"    va=tom_epoch(gmm,tom,val_dl,  tom_opt,False)\n"
"    tom_sch.step(va[0])\n"
"    lr=tom_opt.param_groups[0]['lr']\n"
"    for k,v in zip(['tr','val','tr_l1','val_l1','tr_pc','val_pc','lr'],\n"
"                   [tr[0],va[0],tr[1],va[1],tr[2],va[2],lr]): tom_h[k].append(v)\n"
"    print(f'Ep{ep:2d}/{TOM_EPOCHS} | tr={tr[0]:.4f}(L1={tr[1]:.4f},VGG={tr[2]:.4f},TV={tr[3]:.4f}) | '\n"
"          f'val={va[0]:.4f}(L1={va[1]:.4f},VGG={va[2]:.4f}) | lr={lr:.6f} | {time.time()-t0:.1f}s')\n"
"    if va[0]<best_vt:\n"
"        best_vt=va[0]; pat_t=0\n"
"        best_tom_w={k:v.cpu().clone() for k,v in tom.state_dict().items()}\n"
"        print('   best TOM saved')\n"
"    else:\n"
"        pat_t+=1\n"
"        if pat_t>=PATIENCE: print(f'  Early stop ep{ep}'); break\n"
"tom.load_state_dict(best_tom_w)\n"
"print(f'TOM best val: {best_vt:.4f}')\n"
))

# ── 20 · TOM curves ──────────────────────────────────────────────────────────
C.append(md("### 6.1 TOM Training Curves"))
C.append(code(
"ep=list(range(1,len(tom_h['tr'])+1))\n"
"fig,axes=plt.subplots(1,3,figsize=(16,4))\n"
"fig.suptitle('TOM Training — Stage 2',fontsize=13,fontweight='bold')\n"
"axes[0].plot(ep,tom_h['tr'],label='Train',color='steelblue',lw=2)\n"
"axes[0].plot(ep,tom_h['val'],label='Val',color='darkorange',lw=2)\n"
"axes[0].set_title('Total Loss'); axes[0].legend(); axes[0].grid(alpha=0.3)\n"
"axes[1].plot(ep,tom_h['tr_l1'],label='Train L1',color='steelblue',lw=2)\n"
"axes[1].plot(ep,tom_h['val_l1'],label='Val L1',color='darkorange',lw=2)\n"
"axes[1].plot(ep,tom_h['tr_pc'],label='Train VGG',color='steelblue',lw=2,ls='--')\n"
"axes[1].plot(ep,tom_h['val_pc'],label='Val VGG',color='darkorange',lw=2,ls='--')\n"
"axes[1].set_title('L1 vs VGG Perceptual'); axes[1].legend(fontsize=9); axes[1].grid(alpha=0.3)\n"
"axes[2].plot(ep,tom_h['lr'],color='purple',lw=2)\n"
"axes[2].set_title('Learning Rate'); axes[2].set_yscale('log'); axes[2].grid(alpha=0.3)\n"
"for ax in axes: ax.set_xlabel('Epoch')\n"
"plt.tight_layout(); plt.savefig('tom_training_curves.png',dpi=100,bbox_inches='tight'); plt.show()\n"
))

# ── 21 · Qualitative results ─────────────────────────────────────────────────
C.append(md(
"## 7. Results <a id='7'></a>\n\n"
"### 7.1 Qualitative Comparison\n"
"Columns: **Person** | **Target Cloth** | **Warped Cloth (GMM)** | **Comp Mask** | **Final Output** | **GT**"
))
C.append(code(
"gmm.eval(); tom.eval()\n"
"N_SHOW=6\n"
"samples=[test_ds[i] for i in range(N_SHOW)]\n"
"batch={k:torch.stack([s[k] for s in samples]) for k in samples[0]}\n\n"
"with torch.no_grad():\n"
"    wc,wm,_     =gmm(batch['agnostic'],batch['cloth'],batch['cloth_mask'])\n"
"    out,ren,msk =tom(torch.cat([batch['agnostic'],wc,wm],dim=1),wc)\n\n"
"col_titles=['Person (GT)','Target Cloth','Warped Cloth','Comp. Mask','Final Output','Ground Truth']\n"
"fig,axes=plt.subplots(N_SHOW,6,figsize=(22,4.3*N_SHOW))\n"
"fig.suptitle('CP-VTON Pipeline — Qualitative Results',fontsize=14,fontweight='bold',y=1.005)\n"
"for row in range(N_SHOW):\n"
"    imgs=[denorm(batch['person'][row]), denorm(batch['cloth'][row]),\n"
"          denorm(wc[row]), msk[row,0].detach().numpy(),\n"
"          denorm(out[row]), denorm(batch['person'][row])]\n"
"    cmaps=[None,None,None,'RdYlGn',None,None]\n"
"    for col,(img,cm,title) in enumerate(zip(imgs,cmaps,col_titles)):\n"
"        axes[row][col].imshow(img,cmap=cm,vmin=0 if cm else None,vmax=1 if cm else None)\n"
"        axes[row][col].axis('off')\n"
"        if row==0: axes[row][col].set_title(title,fontsize=9,fontweight='bold')\n"
"    axes[row][0].set_ylabel(f'Test {row+1}',fontsize=10)\n"
"plt.tight_layout(); plt.savefig('final_results.png',dpi=100,bbox_inches='tight'); plt.show()\n"
))

# ── 22 · Quantitative metrics ────────────────────────────────────────────────
C.append(md("### 7.2 Quantitative Metrics (100 test pairs)"))
C.append(code(
"def metrics_batch(pred_t, gt_t):\n"
"    sl,pl,ml=[],[],[]\n"
"    for p,g in zip(pred_t,gt_t):\n"
"        pn=(p*0.5+0.5).clamp(0,1).permute(1,2,0).detach().numpy()\n"
"        gn=(g*0.5+0.5).clamp(0,1).permute(1,2,0).detach().numpy()\n"
"        sl.append(ssim(pn,gn,data_range=1.0,channel_axis=2))\n"
"        pl.append(psnr(gn,pn,data_range=1.0))\n"
"        ml.append(float(np.mean((pn-gn)**2)))\n"
"    return sl,pl,ml\n\n"
"gmm.eval(); tom.eval()\n"
"s_nc,p_nc,m_nc=[],[],[]\n"
"s_cp,p_cp,m_cp=[],[],[]\n\n"
"with torch.no_grad():\n"
"    for b in test_dl:\n"
"        wc,wm,_=gmm(b['agnostic'],b['cloth'],b['cloth_mask'])\n"
"        out,_,_=tom(torch.cat([b['agnostic'],wc,wm],dim=1),wc)\n"
"        sl,pl,ml=metrics_batch(b['agnostic'],b['person'])\n"
"        s_nc+=sl; p_nc+=pl; m_nc+=ml\n"
"        sl,pl,ml=metrics_batch(out,b['person'])\n"
"        s_cp+=sl; p_cp+=pl; m_cp+=ml\n\n"
"res=pd.DataFrame({\n"
"    'Method':['No-Change Baseline','CP-VTON Pipeline (Ours)'],\n"
"    'SSIM_up':[np.mean(s_nc),np.mean(s_cp)],\n"
"    'PSNR_up':[np.mean(p_nc),np.mean(p_cp)],\n"
"    'MSE_dn': [np.mean(m_nc),np.mean(m_cp)],\n"
"})\n"
"print(res.to_string(index=False,float_format='{:.4f}'.format))\n\n"
"fig,axes=plt.subplots(1,3,figsize=(14,4))\n"
"fig.suptitle('Quantitative Evaluation (100 test pairs)',fontsize=13,fontweight='bold')\n"
"for ax,metric,vals in zip(axes,\n"
"    ['SSIM (higher=better)','PSNR (higher=better)','MSE (lower=better)'],\n"
"    [[np.mean(s_nc),np.mean(s_cp)],[np.mean(p_nc),np.mean(p_cp)],[np.mean(m_nc),np.mean(m_cp)]]):\n"
"    bars=ax.bar(['Baseline','Ours'],vals,color=['#e74c3c','#2ecc71'],edgecolor='white',width=0.5)\n"
"    ax.set_title(metric); ax.grid(axis='y',alpha=0.3)\n"
"    for bar,val in zip(bars,vals):\n"
"        ax.text(bar.get_x()+bar.get_width()/2,bar.get_height()*1.01,f'{val:.4f}',\n"
"                ha='center',va='bottom',fontsize=10,fontweight='bold')\n"
"plt.tight_layout(); plt.savefig('quantitative_metrics.png',dpi=100,bbox_inches='tight'); plt.show()\n"
))

# ── 23 · Overfitting analysis ────────────────────────────────────────────────
C.append(md("## 8. Overfitting Analysis <a id='8'></a>\nBoth stages are analysed independently."))
C.append(code(
"ge=len(gmm_h['tr']); te=len(tom_h['tr'])\n"
"gg=abs(gmm_h['val'][-1]-gmm_h['tr'][-1])\n"
"tg=abs(tom_h['val'][-1]-tom_h['tr'][-1])\n"
"print('='*58); print('OVERFITTING ANALYSIS'); print('='*58)\n"
"print(f'{\"\":22s} {\"GMM\":>10s} {\"TOM\":>10s}')\n"
"print('-'*44)\n"
"print(f'{\"Epochs trained\":22s} {ge:>10d} {te:>10d}')\n"
"print(f'{\"Final train loss\":22s} {gmm_h[\"tr\"][-1]:>10.4f} {tom_h[\"tr\"][-1]:>10.4f}')\n"
"print(f'{\"Final val loss\":22s} {gmm_h[\"val\"][-1]:>10.4f} {tom_h[\"val\"][-1]:>10.4f}')\n"
"print(f'{\"Train-Val gap\":22s} {gg:>10.4f} {tg:>10.4f}')\n\n"
"ao=pd.DataFrame({\n"
"    'Technique':['Dropout','L2 weight decay','Data augmentation','Early stopping',\n"
"                 'LR scheduling','Gradient clipping','TPS reg (GMM)','Mask TV (TOM)','VGG loss (TOM)'],\n"
"    'Detail':[\n"
"        '0.1/0.2/0.3 per encoder level',\n"
"        f'Adam weight_decay={WEIGHT_DECAY}',\n"
"        'Horizontal flip (geometry safe)',\n"
"        f'patience={PATIENCE} both stages',\n"
"        'ReduceLROnPlateau factor=0.5 patience=3',\n"
"        'max_norm=1.0',\n"
"        'L2 on theta -> smooth warps',\n"
"        'Total variation on composition mask',\n"
"        f'VGG relu1_2/2_2/3_3 weight={VGG_W}',\n"
"    ]\n"
"})\n"
"print(); print(ao.to_string(index=False))\n\n"
"fig,axes=plt.subplots(2,2,figsize=(14,9))\n"
"fig.suptitle('Overfitting Analysis',fontsize=14,fontweight='bold')\n"
"for (stage,hist),axrow in zip([('GMM',gmm_h),('TOM',tom_h)],[0,1]):\n"
"    ep=list(range(1,len(hist['tr'])+1))\n"
"    ax=axes[axrow][0]\n"
"    ax.plot(ep,hist['tr'],label='Train',color='steelblue',lw=2)\n"
"    ax.plot(ep,hist['val'],label='Val',color='darkorange',lw=2)\n"
"    ax.fill_between(ep,hist['tr'],hist['val'],alpha=0.12,color='red')\n"
"    ax.set_title(f'{stage} Total Loss'); ax.legend(); ax.grid(alpha=0.3); ax.set_xlabel('Epoch')\n"
"    ax2=axes[axrow][1]\n"
"    gaps=[abs(v-t) for v,t in zip(hist['val'],hist['tr'])]\n"
"    ax2.bar(ep,gaps,color='salmon',edgecolor='darkred',linewidth=0.4)\n"
"    ax2.axhline(np.mean(gaps),color='darkred',ls='--',lw=2,label=f'Mean={np.mean(gaps):.4f}')\n"
"    ax2.set_title(f'{stage} |Val-Train| Gap'); ax2.legend(); ax2.grid(alpha=0.3,axis='y'); ax2.set_xlabel('Epoch')\n"
"plt.tight_layout(); plt.savefig('overfitting_analysis.png',dpi=100,bbox_inches='tight'); plt.show()\n"
))

# ── 24 · Conclusion ──────────────────────────────────────────────────────────
C.append(md(
"## 9. Conclusion & References <a id='9'></a>\n\n"
"### Summary\n\n"
"| Stage | Module | CV Technique | Role |\n|---|---|---|---|\n"
"| 1 | **GMM** | CNN correlation + TPS warping | Geometric cloth alignment |\n"
"| 2 | **TOM** | U-Net + composition mask | Photo-realistic synthesis |\n"
"| — | **VGG perceptual loss** | Pretrained VGG-16 features | Texture/semantic fidelity |\n\n"
"### Limitations\n"
"- Training on 600 pairs limits generalisation; full 11 k pairs recommended.\n"
"- TPS per-sample solve loop is the CPU bottleneck (GPU batch-solve would be faster).\n"
"- No GAN discriminator — WGAN-GP typically sharpens textures further.\n"
"- Agnostic representation leaves residual of original clothing.\n\n"
"### Future Work\n"
"- Full VITON-HD training at 512×384.\n"
"- Adversarial (GAN) training for sharper outputs.\n"
"- ALIAS normalization for misalignment robustness (VITON-HD style).\n"
"- Lower-body and full-body garment extension.\n\n"
"---\n\n"
"### References\n\n"
"1. **CP-VTON**: Wang et al., *Toward Characteristic-Preserving Image-based Virtual Try-On Network.* ECCV 2018.\n"
"2. **VITON-HD**: Choi et al., *VITON-HD: High-Resolution Virtual Try-On via Misalignment-Aware Normalization.* CVPR 2021.\n"
"3. **U-Net**: Ronneberger et al., *U-Net: Convolutional Networks for Biomedical Image Segmentation.* MICCAI 2015.\n"
"4. **OpenPose**: Cao et al., *OpenPose: Realtime Multi-Person 2D Pose Estimation.* IEEE TPAMI 2019.\n"
"5. **Perceptual Loss**: Johnson et al., *Perceptual Losses for Real-Time Style Transfer.* ECCV 2016.\n"
"6. **STN/TPS**: Jaderberg et al., *Spatial Transformer Networks.* NeurIPS 2015.\n"
"7. **SSIM**: Wang et al., *Image Quality Assessment: From Error Visibility to Structural Similarity.* IEEE TIP 2004.\n"
"8. **Adam**: Kingma & Ba, *Adam: A Method for Stochastic Optimization.* ICLR 2015.\n"
))

# ── Assemble & write ──────────────────────────────────────────────────────────
nb.cells = C
OUT = "./virtual_tryon_v2.ipynb"
nbf.write(nb, OUT)
print(f"Written {len(C)} cells -> {OUT}")
